import random


topics = [ 
    'VPC Endpoint',
    'AWS PrivateLink',
    'AWS Trusted Advisor',
    'Amazon GuardDuty',
    'Amazon Inspector',
    'AWS Shield',
    'Amazon Kinesis Data Streams',
    'Amazon Kinesis Data Firehose',
    'Amazon Kinesis Data Alanytics',
    'AWS Config',
    'AWS CloudTrail',
    'AWS CloudWatch',
    'AWS Snowball',
    'Amazon AppFlow',
    'AWS Key Mamagement Service (KMS)',
    'Amazon SegaMaker',
    'Amazon Comprehend',
    'Rekognition',
    'Amazon FSx',
    'AWS Elatic Beanstalk',
    'Amazon S3 File Gateway',
    'Amazon Aurora',
    'AWS Global Accelerator',
    'AWS Database Migration Service',
    'AWS Organizations',
    'AmazonMQ',
    'Amazon QuickSight',
    'AWS Amplify',
    'AWS Control Tower',
    'Amazon S3 Object Rock Retention',
    'Amazon OpenSearch Service',
    'Amazon Athena',
    'Amazon FSx',
    'Origin Access Identity (OAI)',
    'Access Contorl List (ACL)',
    'Web Application Firewall (WAF)',
    'Amazon RDS Proxy',
    'Amazon DynamoDB Accelerator (DAX)',
    'Amazon Data Lifecycle Manager (DLM)',
    'AWS Identity and Access Management (IAM)',
    'taskRoleArn',
    'Read Replica',
    'AWS Elastic Beanstalk',
    'AWS Direct Connect',
    'Amazon CloudFront',
    'Amazon Redshift',
    'AWS Lake Formation',
    'SSE-S3',
    'Amazon Pinpoint',
    'Amazon DynamoDB TTL',
    'Amazon DynamoDB Streams',
    'Amazon Textract',
    'Amazon Cognito',
    'Amazon SNS',
    'Amazon SES',
    'Amazon SQS',
    'SQS Visibility Timeout',
    'Amazon EventBridge',
    'Amazon ElastiCache',
    'Backlog Metric',
]

result = random.sample(topics, 10)
print(result)